config/routes.rb
Rails.application.routes.draw do
  resources :overalls

  resources :amortizations

  resources :sales

  resources :quotes

  resources :emp_types

  resources :employees

  resources :customers

  resources :years

  resources :colors

  resources :makes

  resources :cars

root 'car#index'

end

app/models/amortization.rb
class Amortization < ActiveRecord::Base
  belongs_to :sale

  def combine_name_price
    "#{quote.quote_name} #{quote.total_price}"
  end

  def calculate_quote
    i = interest/100
    t = quote.total_price
    u = terms * 12
    m = ((i * t * (1+i)**t)/(((1+i)**u)-1))
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :make
  belongs_to :color
  belongs_to :year
  has_many :quotes
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/emp_type.rb
class EmpType < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes
  belongs_to :emp_type
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/overall.rb
class Overall < ActiveRecord::Base
  belongs_to :sale
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :employee
  has_many :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  has_many :overalls
  has_many :amortizations
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
    @cars = Car.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote_name, :mark_price, :tax, :total_price, :date_started, :sold, :car_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/emp_types_helper.rb
module EmpTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/overalls_helper.rb
module OverallsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_name %><br>
    <%= f.text_field :quote_name %>
  </div>
    <div class="field">
      <%= f.label :car_name, "VIN Number" %><br>
      <%= f.collection_select :car_id, Car.all, :id, :vin_num %>
    </div>
  <div class="field">
    <%= f.label :mark_price %><br>
    <%= f.text_field :mark_price %>
  </div>
  <div class="field">
    <%= f.label :tax %><br>
    <%= f.number_field :tax %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.number_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :date_started %><br>
    <%= f.date_select :date_started %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.check_box :sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Quote name</th>
      <th>Car</th>
      <th>Mark price</th>
      <th>Tax</th>
      <th>Total price</th>
      <th>Date started</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote_name %></td>
        <td><%= quote.car.vin_num %></td>
        <td><%= quote.mark_price %></td>
        <td><%= quote.tax %></td>
        <td><%= quote.total_price %></td>
        <td><%= quote.date_started %></td>
        <td><%= quote.sold %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote name:</strong>
  <%= @quote.quote_name %>
</p>

<p>
  <strong>Mark price:</strong>
  <%= @quote.mark_price %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @quote.tax %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @quote.total_price %>
</p>

<p>
  <strong>Date started:</strong>
  <%= @quote.date_started %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @quote.sold %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car_id %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>