config/routes.rb
Rails.application.routes.draw do
  resources :overalls

  resources :amortizations

  resources :sales

  resources :quotes

  resources :emp_types

  resources :employees

  resources :customers

  resources :years

  resources :colors

  resources :makes

  resources :cars

root 'car#index'

end

app/models/amortization.rb
class Amortization < ActiveRecord::Base
  belongs_to :sale

  def combine_name_price
    "#{quote.quote_name} #{quote.total_price}"
  end

  def calculate_quote
    i = interest/100
    t = quote.total_price
    u = terms * 12
    m = ((i * t * (1+i)**t)/(((1+i)**u)-1))
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :make
  belongs_to :color
  belongs_to :year
  has_many :quotes
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/emp_type.rb
class EmpType < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes
  belongs_to :emp_type
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/overall.rb
class Overall < ActiveRecord::Base
  belongs_to :sale
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :employee
  has_many :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  has_many :overalls
  has_many :amortizations
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:fname, :lname, :phone, :email, :emp_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/emp_types_helper.rb
module EmpTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/overalls_helper.rb
module OverallsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, "First Name" %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname, "Last Night" %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone" %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :emp_type, "Employee Position" %><br>
    <%= f.collection_select :emp_type, EmpType.all, :id, :emp_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Employees</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Employee Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.fname %></td>
        <td><%= employee.lname %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
        <td><%= employee.emp_type.emp_type %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @employee.fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @employee.lname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Employee Type:</strong>
  <%= @employee.emp_type %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>