config/routes.rb
Rails.application.routes.draw do
  resources :overalls

  resources :amortizations

  resources :sales

  resources :quotes

  resources :emp_types

  resources :employees

  resources :customers

  resources :years

  resources :colors

  resources :makes

  resources :cars

root 'car#index'

end

app/models/amortization.rb
class Amortization < ActiveRecord::Base
  belongs_to :sale

  def combine_name_price
    "#{quote.quote_name} #{quote.total_price}"
  end

  def calculate_quote
    i = interest/100
    t = quote.total_price
    u = terms * 12
    m = ((i * t * (1+i)**t)/(((1+i)**u)-1))
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :make
  belongs_to :color
  belongs_to :year
  has_many :quotes
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/emp_type.rb
class EmpType < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes
  belongs_to :emp_type
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/overall.rb
class Overall < ActiveRecord::Base
  belongs_to :sale
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :employee
  has_many :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  has_many :overalls
  has_many :amortizations
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/amortizations_controller.rb
class AmortizationsController < ApplicationController
  before_action :set_amortization, only: [:show, :edit, :update, :destroy]

  # GET /amortizations
  # GET /amortizations.json
  def index
    @amortizations = Amortization.all
  end

  # GET /amortizations/1
  # GET /amortizations/1.json
  def show
  end

  # GET /amortizations/new
  def new
    @amortization = Amortization.new
  end

  # GET /amortizations/1/edit
  def edit
  end

  # POST /amortizations
  # POST /amortizations.json
  def create
    @amortization = Amortization.new(amortization_params)

    respond_to do |format|
      if @amortization.save
        format.html { redirect_to @amortization, notice: 'Amortization was successfully created.' }
        format.json { render :show, status: :created, location: @amortization }
      else
        format.html { render :new }
        format.json { render json: @amortization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amortizations/1
  # PATCH/PUT /amortizations/1.json
  def update
    respond_to do |format|
      if @amortization.update(amortization_params)
        format.html { redirect_to @amortization, notice: 'Amortization was successfully updated.' }
        format.json { render :show, status: :ok, location: @amortization }
      else
        format.html { render :edit }
        format.json { render json: @amortization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amortizations/1
  # DELETE /amortizations/1.json
  def destroy
    @amortization.destroy
    respond_to do |format|
      format.html { redirect_to amortizations_url, notice: 'Amortization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amortization
      @amortization = Amortization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amortization_params
      params.require(:amortization).permit(:term_years, :interest, :month_pay, :sale_id)
    end
end

app/helpers/amortizations_helper.rb
module AmortizationsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/emp_types_helper.rb
module EmpTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/overalls_helper.rb
module OverallsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/amortizations/_form.html.erb
<%= form_for(@amortization) do |f| %>
  <% if @amortization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amortization.errors.count, "error") %> prohibited this amortization from being saved:</h2>

      <ul>
      <% @amortization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term_years %><br>
    <%= f.number_field :term_years %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :month_pay, "Monthly Payments" %><br>
    <%= f.number_field :month_pay %>
  </div>
  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.number_field :sale_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amortizations/edit.html.erb
<h1>Editing Amortization</h1>

<%= render 'form' %>

<%= link_to 'Show', @amortization %> |
<%= link_to 'Back', amortizations_path %>

app/views/amortizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amortization Table</h1>

<table>
  <thead>
    <tr>
      <th>Term years</th>
      <th>Interest</th>
      <th>Month pay</th>
      <th>Sale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amortizations.each do |amortization| %>
      <tr>
        <td><%= amortization.term_years %></td>
        <td><%= amortization.interest %></td>
        <td><%= amortization.month_pay %></td>
        <td><%= amortization.sale_id %></td>
        <td><%= link_to 'Show', amortization %></td>
        <td><%= link_to 'Edit', edit_amortization_path(amortization) %></td>
        <td><%= link_to 'Destroy', amortization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amortization', new_amortization_path %>

app/views/amortizations/new.html.erb
<h1>New Amortization</h1>

<%= render 'form' %>

<%= link_to 'Back', amortizations_path %>

app/views/amortizations/show.html.erb
<html>
<body>

<p id="notice"><%= notice %></p>


<p>
  <strong>Quote Price</strong>
  <%= @amortization.sale.sale_total%>
</p>

<p>
  <strong>Terms (Years):</strong>
  <%= @amortization.term_years %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @amortization.interest %>
</p>


<%= link_to 'Edit', edit_amortization_path(@amortization) %> |
<%= link_to 'Back', amortization_path %>


<div id="something"></div>
<div id = "table"></div>

<script type="text/javascript">



    var principal = <%= @amortization.quote.total_price %>
    var annualInterest = <%= @amortization.interest %>/100
    var lengthYears = <%= @amortization.term_years %>

    var monthlyInterest = annualInterest/(12);
    var numberOfMonths = lengthYears*12;
    var monthlyPayment = ((monthlyInterest * principal * Math.pow((1 + monthlyInterest),numberOfMonths))/((Math.pow((1 + monthlyInterest),numberOfMonths))-1))

    var paymentInterest, principalPayment;
    document.getElementById('something').innerHTML = 'Monthly Payment: $'+monthlyPayment.toFixed(2)+'<p>';

    var table = document.createElement('table');
    var header1 = document.createElement('th');
    var header2 = document.createElement('th');
    var header3 = document.createElement('th');
    var header4 = document.createElement('th');

    var monthHeader1 = document.createTextNode('Month');
    var monthHeader2 = document.createTextNode('Interest');
    var monthHeader3 = document.createTextNode('Principal');
    var monthHeader4 = document.createTextNode('Balance');

    header1.appendChild(monthHeader1);
    header2.appendChild(monthHeader2);
    header3.appendChild(monthHeader3);
    header4.appendChild(monthHeader4);

    table.appendChild(header1);
    table.appendChild(header2);
    table.appendChild(header3);
    table.appendChild(header4);

    for( var i = 1; i<=numberOfMonths; i++){

        var tr = document.createElement('tr')

        paymentInterest =  (principal*monthlyInterest);
        principalPayment = (monthlyPayment - paymentInterest);
        principal -= principalPayment;

        var td1 = document.createElement('td')
        var td2= document.createElement('td')
        var td3= document.createElement('td')
        var td4 = document.createElement('td')

        var text1 = document.createTextNode(i);
        var text2 = document.createTextNode(paymentInterest.toFixed(2));
        var text3 = document.createTextNode(principalPayment.toFixed(2));
        var text4 = document.createTextNode(principal.toFixed(2));

        td1.appendChild(text1);
        td2.appendChild(text2);
        td3.appendChild(text3);
        td4.appendChild(text4);

        tr.appendChild(td1);
        tr.appendChild(td2);
        tr.appendChild(td3);
        tr.appendChild(td4);

        table.appendChild(tr);
    }
    document.body.appendChild(table);
</script>

</body>
</html>