config/routes.rb
Rails.application.routes.draw do
  resources :overalls

  resources :amortizations

  resources :sales

  resources :quotes

  resources :emp_types

  resources :employees

  resources :customers

  resources :years

  resources :colors

  resources :makes

  resources :cars

root 'car#index'

end

app/models/amortization.rb
class Amortization < ActiveRecord::Base
  belongs_to :sale

  def combine_name_price
    "#{quote.quote_name} #{quote.total_price}"
  end

  def calculate_quote
    i = interest/100
    t = quote.total_price
    u = terms * 12
    m = ((i * t * (1+i)**t)/(((1+i)**u)-1))
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :make
  belongs_to :color
  belongs_to :year
  has_many :quotes
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :cars
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/emp_type.rb
class EmpType < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes
  belongs_to :emp_type
  def full_name
    "#{fname} #{lname}"
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :cars
end

app/models/overall.rb
class Overall < ActiveRecord::Base
  belongs_to :sale
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :employee
  has_many :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :quote
  has_many :overalls
  has_many :amortizations
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cars
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:sale_total, :quote_id, :customer_id, :employee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/emp_types_helper.rb
module EmpTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/overalls_helper.rb
module OverallsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sale_total %><br>
    <%= f.number_field :sale_total %>
  </div>
  <div class="field">
    <%= f.label :quote_id %><br>
    <%= f.number_field :quote_id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Sale total</th>
      <th>Quote</th>
      <th>Customer</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.sale_total %></td>
        <td><%= sale.quote_id %></td>
        <td><%= sale.customer_id %></td>
        <td><%= sale.employee_id %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale total:</strong>
  <%= @sale.sale_total %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @sale.quote_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @sale.employee_id %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>